services:
    mu_news_module.hook_subscriber.filter_hooks.messages:
        class: MU\NewsModule\HookSubscriber\MessageFilterHooksSubscriber
        arguments:
            - "@translator.default"
        tags:
            - { name: zikula.hook_subscriber, areaName: 'subscriber.munewsmodule.filter_hooks.messages' }

    mu_news_module.hook_subscriber.form_aware_hook.messages:
        class: MU\NewsModule\HookSubscriber\MessageFormAwareHookSubscriber
        arguments:
            - "@translator.default"
        tags:
            - { name: zikula.hook_subscriber, areaName: 'subscriber.munewsmodule.form_aware_hook.messages' }

    mu_news_module.hook_subscriber.ui_hooks.messages:
        class: MU\NewsModule\HookSubscriber\MessageUiHooksSubscriber
        arguments:
            - "@translator.default"
        tags:
            - { name: zikula.hook_subscriber, areaName: 'subscriber.munewsmodule.ui_hooks.messages' }

    mu_news_module.hook_provider.filter_hooks.provider:
        class: MU\NewsModule\HookProvider\FilterHooksProvider
        arguments:
            - "@translator.default"
        tags:
            - { name: zikula.hook_provider, areaName: 'provider.munewsmodule.filter_hooks.news' }

    mu_news_module.hook_provider.form_aware_hook.messages:
        class: MU\NewsModule\HookProvider\MessageFormAwareHookProvider
        arguments:
            - "@translator.default"
            - "@session"
            - "@form.factory"
        tags:
            - { name: zikula.hook_provider, areaName: 'provider.munewsmodule.form_aware_hook.messages' }

